### ISSUE TITLE
Import data operation is not atomic

### ISSUE THREAD

**Issue by niqiukun** [CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g11#30]
**Describe the bug**
The upload author record operation can fail while the version is still successfully created.

**To Reproduce**
To be investigated.

**Expected behavior**
Both should succeed / fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/5328196/95327090-1e576680-08d6-11eb-9f3e-9964c3a31d0a.png)

**Comment by madanalogy** [comment]
Data importing: if the frontend sends the request to `/record` endpoint first, the version will not get created and you get an error trying to create the record. After the version is created, trying to create the record again will succeed.

Server response from the `/record` endpoint:
message: "`org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : sg.edu.nus.comp.cs3219.viz.common.entity.record.AuthorRecord.version -> sg.edu.nus.comp.cs3219.viz.common.entity.record.Version; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : sg.edu.nus.comp.cs3219.viz.common.entity.record.AuthorRecord.version -> sg.edu.nus.comp.cs3219.viz.common.entity.record.Version`"

**Comment by jhocx** [comment]
Solution TODO:
Move Version Logic into Record Logic to ensure that the version is already created during creation of the record.
